# Docker Compose to set up api and db in sync

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile.local.api
    image: resy-takehome-backend
    ports: 
      - 49160:8080
    links: 
      - db:postgres
    depends_on: 
      - db
      - cache
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
  db:
    build:
      context: .
      dockerfile: Dockerfile.local.db
    image: postgres
    # restart: always
    ports: 
      - 5432:5432
    command: ["postgres", "-c", "log_statement=all"]
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: pursuit
      POSTGRES_PASSWORD: pursuit2022